export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const CREATE_OPERATION = 'CREATE_OPERATION';

export const DELETE_OPERATION = 'DELETE_OPERATION';

export const SAVE_SALAIRE = 'SAVE_SALAIRE';